### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Helveg** [hakonsbm/nest-simulator#45]
```
Building wheel...

    + rm -rf /tmp/cibuildwheel/built_wheel
    + mkdir -p /tmp/cibuildwheel/built_wheel
    + python -m pip wheel /project --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps
  error: subprocess-exited-with-error

  × Building wheel for nest-simulator (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [437 lines of output]
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /opt/rh/devtoolset-10/root/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /opt/rh/devtoolset-10/root/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /project/_cmake_test_compile/build
      -- The CXX compiler identification is GNU 10.2.1
      -- The C compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /opt/rh/devtoolset-10/root/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /opt/rh/devtoolset-10/root/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
      -- Looking for include file inttypes.h
      -- Looking for include file inttypes.h - found
      -- Looking for include file mach-o/dyld.h
      -- Looking for include file mach-o/dyld.h - not found
      -- Looking for include file mach/mach.h
      -- Looking for include file mach/mach.h - not found
      -- Looking for include file memory.h
      -- Looking for include file memory.h - found
      -- Looking for include file stdint.h
      -- Looking for include file stdint.h - found
      -- Looking for include file sys/types.h
      -- Looking for include file sys/types.h - found
      -- Looking for C++ include istream
      -- Looking for C++ include istream - found
      -- Looking for C++ include ostream
      -- Looking for C++ include ostream - found
      -- Looking for C++ include sstream
      -- Looking for C++ include sstream - found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of long long
      -- Check size of long long - done
      -- Check size of u_int16_t
      -- Check size of u_int16_t - done
      -- Check size of uint16_t
      -- Check size of uint16_t - done
      -- Check size of u_int64_t
      -- Check size of u_int64_t - done
      -- Check size of uint64_t
      -- Check size of uint64_t - done
      -- Looking for NAN
      -- Looking for NAN - found
      -- Looking for isnan
      -- Looking for isnan - found
      -- Looking for M_E
      -- Looking for M_E - found
      -- Looking for M_PI
      -- Looking for M_PI - found
      -- Looking for expm1
      -- Looking for expm1 - not found
      -- Host triple: x86_64-pc-linux
      -- Target triple: x86_64-pc-linux
      -- Found Python: /opt/python/cp38-cp38/bin/python (found suitable version "3.8.13", minimum required is "3.8") found components: Interpreter Development.Module
      -- Found Cython: /tmp/pip-build-env-v4w_7q17/overlay/bin/cython (found suitable version "0.29.30", minimum required is "0.28.3")
      -- Found LTDL: /usr/local/lib/libltdl.so (found version "2.4.7")
      -- Could NOT find Readline (missing: READLINE_LIBRARY NCURSES_LIBRARY READLINE_INCLUDE_DIR)
      -- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
      -- Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY) (found version "")
      -- Found OpenMP_C: -fopenmp (found version "4.5")
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- Found Boost: /boost (found suitable version "1.79.0", minimum required is "1.69.0")
      -- Check the abort exitcode.
      -- Check the abort exitcode. Permission denied
      -- Check the segmentation fault exitcode.
      -- Check the segmentation fault exitcode. Permission denied
      -- Check whether the compiler ignores cmath makros.
      -- Check whether the compiler ignores cmath makros. OFF
      -- Check whether the compiler does NOT include <*.h> headers ISO conformant.
      -- Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF
      -- Check whether the compiler respects symbolic signal names in signal.h.
      -- Check whether the compiler respects symbolic signal names in signal.h. OFF
      -- Check static template member declaration.
      -- Check static template member declaration. OFF
      -- Check for STL vector capacity base unity.
      -- Check for STL vector capacity base unity. ON
      -- Check for STL vector capacity doubling strategy.
      -- Check for STL vector capacity doubling strategy. ON
      -- Check whether the compiler fails with ICE.
      -- Check whether the compiler fails with ICE. OFF
      -- Check if ::nan is available from cmath.
      -- Check if ::nan is available from cmath. ON
      -- Check if ::isnan is available from cmath.
      -- Check if ::isnan is available from cmath. ON
      -- Check if Random123 generators work.
      -- Check if Random123 generators work. ON
      -- NEST version: reinvention-of-the-wheel@6880e7c669
      -- Found PythonInterp: /opt/python/cp38-cp38/bin/python (found version "3.8.13")
      -- Wheel build, installing pynestkernel and nestkernel_api to lib64/nest/

      --------------------------------------------------------------------------------
      NEST Configuration Summary
      --------------------------------------------------------------------------------

      Build type          : Release
      Target System       : Linux
      Cross Compiling     : FALSE
      C compiler          : GNU 10.2.1 (/opt/rh/devtoolset-10/root/usr/bin/cc)
      C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto   -O3 -DNDEBUG
      C++ compiler        : GNU 10.2.1 (/opt/rh/devtoolset-10/root/usr/bin/c++)
      C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto -O3 -DNDEBUG
      Build dynamic       : ON

      Built-in modules    : models
      User modules        : None
      Python bindings     : Yes (Python 3.8.13: /opt/python/cp38-cp38/bin/python)
             Includes     : /opt/_internal/cpython-3.8.13/include/python3.8
             Libraries    :

      Cython bindings     : Yes (Cython 0.29.30: /tmp/pip-build-env-v4w_7q17/overlay/bin/cython)
      MPI4PY header           : NO
      Use threading       : Yes (OpenMP: -fopenmp)
      Use GSL             : No
      Use Readline        : No
      Use libltdl         : Yes (LTDL 2.4.7)
          Includes        : /usr/local/include
          Libraries       : /usr/local/lib/libltdl.so

      Use doxygen         : No
      Use MPI             : No
      Detailed timers     : No

      Use MUSIC           : No
      Use libneurosim     : No
      Use Boost           : Yes (Boost 1.79.0)
          Includes        : /boost
          Libraries       :

      Use SIONlib         : No

      --------------------------------------------------------------------------------

      The NEST executable will be installed to:
        /project/_skbuild/linux-x86_64-3.8/cmake-install/bin/

      NEST dynamic libraries and user modules will be installed to:
        /project/_skbuild/linux-x86_64-3.8/cmake-install/lib64/nest/

      Documentation and examples will be installed to:
        /project/_skbuild/linux-x86_64-3.8/cmake-install/share/doc/nest/

      PyNEST will be installed to:
          /project/_skbuild/linux-x86_64-3.8/cmake-install/lib64/python3.8/site-packages

      To set necessary environment variables, add the following line
      to your ~/.bashrc :
        source /project/_skbuild/linux-x86_64-3.8/cmake-install/bin/nest_vars.sh

      --------------------------------------------------------------------------------


      ATTENTION!
      You are about to compile NEST without the GNU Scientific
      Library or your GSL is too old (before v1.11). This means
      that conductance-based neuron models and some random number
      generators will not be available.

      --------------------------------------------------------------------------------

      You can now build and install NEST with
        make
        make install
        make installcheck

      If you experience problems with the installation or the use of NEST,
      please see https://www.nest-simulator.org/frequently_asked_questions
      or go to https://www.nest-simulator.org/community to find out how to
      join the user mailing list.

      -- Configuring done
      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:

          PYTHON_INCLUDE_DIR
          PYTHON_LIBRARY
          Python3_EXECUTABLE
          Python3_INCLUDE_DIR
          Python3_LIBRARY
          SKBUILD


      -- Build files have been written to: /project/_skbuild/linux-x86_64-3.8/cmake-build
      [1/236] Building CXX object models/CMakeFiles/models.dir/aeif_psc_exp.cpp.o
      [2/236] Building CXX object models/CMakeFiles/models.dir/aeif_cond_alpha.cpp.o
      [3/236] Building CXX object models/CMakeFiles/models.dir/aeif_psc_alpha.cpp.o
      [4/236] Building CXX object models/CMakeFiles/models.dir/aeif_psc_delta.cpp.o
      [5/236] Building CXX object models/CMakeFiles/models.dir/aeif_psc_delta_clopath.cpp.o
      [6/236] Building CXX object models/CMakeFiles/models.dir/aeif_cond_exp.cpp.o
      [7/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/numerics.cpp.o
      [8/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/propagator_stability.cpp.o
      [9/236] Building CXX object models/CMakeFiles/models.dir/aeif_cond_alpha_multisynapse.cpp.o
      [10/236] Building CXX object models/CMakeFiles/models.dir/aeif_cond_beta_multisynapse.cpp.o
      [11/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/stopwatch.cpp.o
      [12/236] Building CXX object models/CMakeFiles/models.dir/gif_cond_exp.cpp.o
      [13/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/logging_event.cpp.o
      [14/236] Building CXX object models/CMakeFiles/models.dir/gif_cond_exp_multisynapse.cpp.o
      [15/236] Building CXX object models/CMakeFiles/models.dir/glif_cond.cpp.o
      [16/236] Building CXX object models/CMakeFiles/models.dir/hh_cond_exp_traub.cpp.o
      [17/236] Building CXX object models/CMakeFiles/models.dir/hh_cond_beta_gap_traub.cpp.o
      [18/236] Building CXX object models/CMakeFiles/models.dir/hh_psc_alpha.cpp.o
      [19/236] Building CXX object models/CMakeFiles/models.dir/hh_psc_alpha_clopath.cpp.o
      [20/236] Building CXX object models/CMakeFiles/models.dir/hh_psc_alpha_gap.cpp.o
      [21/236] Building CXX object models/CMakeFiles/models.dir/ht_neuron.cpp.o
      [22/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o
      [23/236] Building CXX object models/CMakeFiles/models.dir/iaf_chxk_2008.cpp.o
      [24/236] Building CXX object models/CMakeFiles/models.dir/iaf_cond_alpha.cpp.o
      [25/236] Building CXX object models/CMakeFiles/models.dir/iaf_cond_alpha_mc.cpp.o
      [26/236] Building CXX object models/CMakeFiles/models.dir/iaf_cond_beta.cpp.o
      [27/236] Building CXX object models/CMakeFiles/models.dir/iaf_cond_exp.cpp.o
      [28/236] Building CXX object models/CMakeFiles/models.dir/iaf_cond_exp_sfa_rr.cpp.o
      [29/236] Building CXX object models/CMakeFiles/models.dir/gif_pop_psc_exp.cpp.o
      [30/236] Building CXX object models/CMakeFiles/models.dir/erfc_neuron.cpp.o
      [31/236] Building CXX object models/CMakeFiles/models.dir/gauss_rate.cpp.o
      [32/236] Building CXX object models/CMakeFiles/models.dir/ginzburg_neuron.cpp.o
      [33/236] Building CXX object libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o
      [34/236] Linking CXX shared library libnestutil/libnestutil.so
      [35/236] Building CXX object models/CMakeFiles/models.dir/gamma_sup_generator.cpp.o
      [36/236] Building CXX object models/CMakeFiles/models.dir/dc_generator.cpp.o
      [37/236] Building CXX object models/CMakeFiles/models.dir/ac_generator.cpp.o
      [38/236] Building CXX object models/CMakeFiles/models.dir/correlospinmatrix_detector.cpp.o
      [39/236] Building CXX object models/CMakeFiles/models.dir/correlation_detector.cpp.o
      [40/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sliregexp.cc.o
      [41/236] Building CXX object models/CMakeFiles/models.dir/amat2_psc_exp.cpp.o
      [42/236] Building CXX object models/CMakeFiles/models.dir/correlomatrix_detector.cpp.o
      [43/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_alpha_canon.cpp.o
      [44/236] Building CXX object models/CMakeFiles/models.dir/iaf_chs_2007.cpp.o
      [45/236] Building CXX object models/CMakeFiles/models.dir/glif_psc.cpp.o
      [46/236] Building CXX object models/CMakeFiles/models.dir/gif_psc_exp.cpp.o
      [47/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_alpha.cpp.o
      [48/236] Building CXX object models/CMakeFiles/models.dir/music_cont_in_proxy.cpp.o
      [49/236] Building CXX object models/CMakeFiles/models.dir/music_cont_out_proxy.cpp.o
      [50/236] Building CXX object models/CMakeFiles/models.dir/music_event_in_proxy.cpp.o
      [51/236] Building CXX object models/CMakeFiles/models.dir/music_event_out_proxy.cpp.o
      [52/236] Building CXX object models/CMakeFiles/models.dir/music_rate_in_proxy.cpp.o
      [53/236] Building CXX object models/CMakeFiles/models.dir/music_rate_out_proxy.cpp.o
      [54/236] Building CXX object models/CMakeFiles/models.dir/music_message_in_proxy.cpp.o
      [55/236] Building CXX object models/CMakeFiles/models.dir/gif_psc_exp_multisynapse.cpp.o
      [56/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_delta.cpp.o
      [57/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_alpha_ps.cpp.o
      [58/236] Building CXX object models/CMakeFiles/models.dir/mcculloch_pitts_neuron.cpp.o
      [59/236] Building CXX object models/CMakeFiles/models.dir/lin_rate.cpp.o
      [60/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_alpha_multisynapse.cpp.o
      [61/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_exp_htum.cpp.o
      [62/236] Building CXX object models/CMakeFiles/models.dir/mip_generator.cpp.o
      [63/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_delta_ps.cpp.o
      [64/236] Building CXX object models/CMakeFiles/models.dir/pp_cond_exp_mc_urbanczik.cpp.o
      [65/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_exp.cpp.o
      [66/236] Building CXX object models/CMakeFiles/models.dir/siegert_neuron.cpp.o
      [67/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_exp_ps_lossless.cpp.o
      [68/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_exp_multisynapse.cpp.o
      [69/236] Building CXX object models/CMakeFiles/models.dir/iaf_psc_exp_ps.cpp.o
      [70/236] Building CXX object models/CMakeFiles/models.dir/mat2_psc_exp.cpp.o
      [71/236] Building CXX object models/CMakeFiles/models.dir/sinusoidal_gamma_generator.cpp.o
      [72/236] Building CXX object models/CMakeFiles/models.dir/multimeter.cpp.o
      [73/236] Building CXX object models/CMakeFiles/models.dir/parrot_neuron.cpp.o
      [74/236] Building CXX object models/CMakeFiles/models.dir/izhikevich.cpp.o
      [75/236] Building CXX object models/CMakeFiles/models.dir/parrot_neuron_ps.cpp.o
      [76/236] Building CXX object models/CMakeFiles/models.dir/noise_generator.cpp.o
      [77/236] Building CXX object models/CMakeFiles/models.dir/poisson_generator_ps.cpp.o
      [78/236] Building CXX object models/CMakeFiles/models.dir/inhomogeneous_poisson_generator.cpp.o
      [79/236] Building CXX object models/CMakeFiles/models.dir/poisson_generator.cpp.o
      [80/236] Building CXX object models/CMakeFiles/models.dir/sigmoid_rate.cpp.o
      [81/236] Building CXX object models/CMakeFiles/models.dir/stdp_pl_synapse_hom.cpp.o
      [82/236] Building CXX object models/CMakeFiles/models.dir/sigmoid_rate_gg_1998.cpp.o
      [83/236] Building CXX object models/CMakeFiles/models.dir/spin_detector.cpp.o
      [84/236] Building CXX object models/CMakeFiles/models.dir/stdp_dopamine_synapse.cpp.o
      [85/236] Building CXX object models/CMakeFiles/models.dir/ppd_sup_generator.cpp.o
      [86/236] Building CXX object models/CMakeFiles/models.dir/pulsepacket_generator.cpp.o
      [87/236] Building CXX object models/CMakeFiles/models.dir/spike_recorder.cpp.o
      [88/236] Building CXX object sli/CMakeFiles/sli_lib.dir/allocator.cpp.o
      [89/236] Building CXX object sli/CMakeFiles/sli_lib.dir/charcode.cc.o
      [90/236] Building CXX object sli/CMakeFiles/sli_lib.dir/booldatum.cc.o
      [91/236] Building CXX object models/CMakeFiles/models.dir/stdp_synapse_hom.cpp.o
      [92/236] Building CXX object models/CMakeFiles/models.dir/pp_psc_delta.cpp.o
      [93/236] Building CXX object sli/CMakeFiles/sli_lib.dir/arraydatum.cc.o
      [94/236] Building CXX object sli/CMakeFiles/sli_lib.dir/datum.cc.o
      [95/236] Building CXX object sli/CMakeFiles/sli_lib.dir/fdstream.cc.o
      [96/236] Building CXX object sli/CMakeFiles/sli_lib.dir/doubledatum.cc.o
      [97/236] Building C object sli/CMakeFiles/sli_lib.dir/get_mem.c.o
      [98/236] Building CXX object models/CMakeFiles/models.dir/spike_generator.cpp.o
      /project/models/spike_generator.cpp: In member function ‘void nest::spike_generator::Parameters_::get(dictionary&) const’:
      /project/models/spike_generator.cpp:69:16: warning: unused variable ‘n_offsets’ [-Wunused-variable]
         69 |   const size_t n_offsets = spike_offsets_.size();
            |                ^~~~~~~~~
      [99/236] Building CXX object models/CMakeFiles/models.dir/pp_pop_psc_delta.cpp.o
      [100/236] Building CXX object sli/CMakeFiles/sli_lib.dir/functiondatum.cc.o
      [101/236] Building CXX object sli/CMakeFiles/sli_lib.dir/integerdatum.cc.o
      [102/236] Building CXX object sli/CMakeFiles/sli_lib.dir/dictstack.cc.o
      [103/236] Building CXX object sli/CMakeFiles/sli_lib.dir/dictutils.cc.o
      [104/236] Building CXX object models/CMakeFiles/models.dir/sinusoidal_poisson_generator.cpp.o
      [105/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slinames.cpp.o
      [106/236] Building CXX object models/CMakeFiles/models.dir/tanh_rate.cpp.o
      [107/236] Building CXX object sli/CMakeFiles/sli_lib.dir/literaldatum.cc.o
      [108/236] Building CXX object sli/CMakeFiles/sli_lib.dir/namedatum.cc.o
      [109/236] Building CXX object sli/CMakeFiles/sli_lib.dir/dict.cc.o
      [110/236] Building CXX object sli/CMakeFiles/sli_lib.dir/name.cc.o
      [111/236] Building CXX object models/CMakeFiles/models.dir/threshold_lin_rate.cpp.o
      [112/236] Building CXX object sli/CMakeFiles/sli_lib.dir/filesystem.cc.o
      /project/sli/filesystem.cc: In member function ‘virtual void FilesystemModule::MoveFileFunction::execute(SLIInterpreter*) const’:
      /project/sli/filesystem.cc:173:11: warning: unused variable ‘t’ [-Wunused-variable]
        173 |       int t = unlink( dst->c_str() );
            |           ^
      [113/236] Building CXX object models/CMakeFiles/models.dir/tsodyks_synapse_hom.cpp.o
      [114/236] Building CXX object sli/CMakeFiles/sli_lib.dir/parser.cc.o
      [115/236] Building CXX object models/CMakeFiles/models.dir/volume_transmitter.cpp.o
      [116/236] Building CXX object sli/CMakeFiles/sli_lib.dir/oosupport.cc.o
      [117/236] Building CXX object models/CMakeFiles/models.dir/spike_dilutor.cpp.o
      [118/236] Building CXX object models/CMakeFiles/models.dir/step_current_generator.cpp.o
      [119/236] Building CXX object models/CMakeFiles/models.dir/weight_recorder.cpp.o
      [120/236] Building CXX object sli/CMakeFiles/sli_lib.dir/scanner.cc.o
      [121/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slibuiltins.cc.o
      [122/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sliexceptions.cc.o
      [123/236] Building CXX object models/CMakeFiles/models.dir/step_rate_generator.cpp.o
      [124/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sliactions.cc.o
      [125/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slitype.cc.o
      [126/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sligraphics.cc.o
      [127/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slistartup.cc.o
      FAILED: sli/CMakeFiles/sli_lib.dir/slistartup.cc.o
      /opt/rh/devtoolset-10/root/usr/bin/c++ -Dsli_lib_EXPORTS -I/boost -I/project/thirdparty -I/project/libnestutil -I/project/_skbuild/linux-x86_64-3.8/cmake-build/libnestutil -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto -O3 -DNDEBUG -fPIC -fopenmp -MD -MT sli/CMakeFiles/sli_lib.dir/slistartup.cc.o -MF sli/CMakeFiles/sli_lib.dir/slistartup.cc.o.d -o sli/CMakeFiles/sli_lib.dir/slistartup.cc.o -c /project/sli/slistartup.cc
      In file included from /project/sli/slistartup.h:30,
                       from /project/sli/slistartup.cc:23:
      /project/sli/slistartup.cc: In member function ‘virtual void SLIStartup::init(SLIInterpreter*)’:
      /project/_skbuild/linux-x86_64-3.8/cmake-build/libnestutil/config.h:48:29: error: ‘Permission’ was not declared in this scope
         48 | #define NEST_EXITCODE_ABORT Permission denied
            |                             ^~~~~~~~~~
      /project/sli/slistartup.cc:476:68: note: in expansion of macro ‘NEST_EXITCODE_ABORT’
        476 |   exitcodes->insert( exitcode_abort_name, Token( new IntegerDatum( NEST_EXITCODE_ABORT ) ) );
            |                                                                    ^~~~~~~~~~~~~~~~~~~
      /project/sli/slistartup.cc:478:51: error: expected primary-expression before ‘(’ token
        478 |   exitcodes->insert( exitcode_segfault_name, Token( new IntegerDatum( NEST_EXITCODE_SEGFAULT ) ) );
            |                                                   ^
      In file included from /project/sli/slistartup.h:30,
                       from /project/sli/slistartup.cc:23:
      /project/_skbuild/linux-x86_64-3.8/cmake-build/libnestutil/config.h:49:43: error: expected ‘)’ before ‘denied’
         49 | #define NEST_EXITCODE_SEGFAULT Permission denied
            |                                           ^~~~~~
      /project/sli/slistartup.cc:478:71: note: in expansion of macro ‘NEST_EXITCODE_SEGFAULT’
        478 |   exitcodes->insert( exitcode_segfault_name, Token( new IntegerDatum( NEST_EXITCODE_SEGFAULT ) ) );
            |                                                                       ^~~~~~~~~~~~~~~~~~~~~~
      /project/sli/slistartup.cc:478:69: note: to match this ‘(’
        478 |   exitcodes->insert( exitcode_segfault_name, Token( new IntegerDatum( NEST_EXITCODE_SEGFAULT ) ) );
            |                                                                     ^
      [128/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slimodule.cc.o
      [129/236] Building CXX object sli/CMakeFiles/sli_lib.dir/symboldatum.cc.o
      [130/236] Building CXX object sli/CMakeFiles/sli_lib.dir/specialfunctionsmodule.cc.o
      [131/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slistack.cc.o
      [132/236] Building CXX object sli/CMakeFiles/sli_lib.dir/interpret.cc.o
      [133/236] Building CXX object sli/CMakeFiles/sli_lib.dir/tarrayobj.cc.o
      [134/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slitypecheck.cc.o
      [135/236] Building CXX object sli/CMakeFiles/sli_lib.dir/stringdatum.cc.o
      [136/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slimath.cc.o
      [137/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slidict.cc.o
      [138/236] Building CXX object sli/CMakeFiles/sli_lib.dir/token.cc.o
      [139/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sli_io.cc.o
      [140/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slidata.cc.o
      [141/236] Building CXX object sli/CMakeFiles/sli_lib.dir/slicontrol.cc.o
      /project/sli/slicontrol.cc: In member function ‘virtual void Forallindexed_aFunction::execute(SLIInterpreter*) const’:
      /project/sli/slicontrol.cc:1037:19: warning: unused variable ‘proc’ [-Wunused-variable]
       1037 |   ProcedureDatum* proc = dynamic_cast< ProcedureDatum* >( i->OStack.top().datum() );
            |                   ^~~~
      /project/sli/slicontrol.cc: In member function ‘virtual void Forallindexed_sFunction::execute(SLIInterpreter*) const’:
      /project/sli/slicontrol.cc:1064:19: warning: unused variable ‘proc’ [-Wunused-variable]
       1064 |   ProcedureDatum* proc = dynamic_cast< ProcedureDatum* >( i->OStack.top().datum() );
            |                   ^~~~
      /project/sli/slicontrol.cc: In member function ‘virtual void Forall_sFunction::execute(SLIInterpreter*) const’:
      /project/sli/slicontrol.cc:1091:19: warning: unused variable ‘proc’ [-Wunused-variable]
       1091 |   ProcedureDatum* proc = dynamic_cast< ProcedureDatum* >( i->OStack.top().datum() );
            |                   ^~~~
      [142/236] Building CXX object sli/CMakeFiles/sli_lib.dir/processes.cc.o
      [143/236] Building CXX object sli/CMakeFiles/sli_lib.dir/sliarray.cc.o
      [144/236] Building CXX object models/CMakeFiles/models.dir/modelsmodule.cpp.o
      ninja: build stopped: subcommand failed.
        File "/tmp/pip-build-env-v4w_7q17/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-v4w_7q17/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 680, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-v4w_7q17/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 704, in make_impl
          raise SKBuildError(


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /project/_skbuild/linux-x86_64-3.8/cmake-build
        Command:
          cmake /project -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/project/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.13 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-v4w_7q17/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/opt/python/cp38-cp38/bin/python -DPython3_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.8.13/include/python3.8 -DPython3_LIBRARY:PATH=libpython3.8.a -DPython_EXECUTABLE:FILEPATH=/opt/python/cp38-cp38/bin/python -DPython_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.8.13/include/python3.8 -DPython_LIBRARY:PATH=libpython3.8.a -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/cp38-cp38/bin/python -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.8.13/include/python3.8 -DPYTHON_LIBRARY:PATH=libpython3.8.a -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-v4w_7q17/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_MODULE_PATH=/project/cmake:/skrepo/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_MODULE_PATH=/project/cmake:/skrepo/skbuild/resources/cmake

      Traceback (most recent call last):

      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /project
        Working directory:
          /project/_skbuild/linux-x86_64-3.8/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nest-simulator
ERROR: Failed to build one or more wheels
WARNING: There was an error checking the latest version of pip.
Processing /project
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: nest-simulator
  Building wheel for nest-simulator (pyproject.toml): started
  Building wheel for nest-simulator (pyproject.toml): still running...
  Building wheel for nest-simulator (pyproject.toml): finished with status 'error'
Failed to build nest-simulator

                                                                     ✕ 134.86s
Error: Command ['python', '-m', 'pip', 'wheel', PurePosixPath('/project'), '--wheel-dir=/tmp/cibuildwheel/built_wheel', '--no-deps'] failed with code 1.

Checking for common errors...
```

Wheel build is failing, something about exitcodes?

**Comment by Helveg** [comment]
Is the problem rooted here?

```
      -- Check the abort exitcode.
      -- Check the abort exitcode. Permission denied
```

Later on `Permission` seems to be used as an exitcode.

**Comment by Helveg** [comment]
The error comes from `CheckExtraCompilerFeatures.cmake`, in the docker image it must somehow not have permissions for one of the steps executed there.

**Comment by Helveg** [comment]
"Fixed" by hardcoding these exitcodes to 255
